In [1]:
import pandas as pd
import re

In [3]:
cat = pd.read_csv('obel-p.tsv', encoding='utf8', sep='\t').fillna('')
cat

,designation,id_text,museum_no,collection,excavation_no,provenience,period,primary_publication,author,publication_date,...,material,object_type,language,sub_genre,accession_no,cdli_comments,atf_source,date_remarks,cdli_collation,electronic_publication
0,"CT 44, 12",P345521,BM 078175,"British Museum, London, UK",,Sippar-Yahrurum,Old Babylonian,"CT 44, 12","Sollberger, Edmond",1963,...,clay,tablet,,,"1888-05-12 Bu, 0004",,no atf,,,
1,"TLB 02, 06",P345845,LB 1823,"de Liagre Böhl Collection, Netherlands Institu...",,,Old Babylonian,"TLB 2, 6 o. ii 14 - r. iii 13","van Dijk, Johannes J. A.",1957,...,clay,tablet,,,,,no atf,,,
2,"CT 42, 08 BM 088288",P283778,BM 088288,"British Museum, London, UK",,,Old Babylonian,"CT 42, 8 = pl. 18-19","Figulla, Hugo H.",1959,...,clay,tablet,Sumerian,,,,no atf,,,
3,"PBS 01/1, 08",P266508,CBS 11359,University of Pennsylvania Museum of Archaeolo...,,Nippur,Old Babylonian,"PBS 1/1, 8","Myhrman, David W.",1911,...,clay,tablet,Sumerian,,,,no atf,,,
4,"VS 02, 010",P342818,VAT 01438 + VAT 01529 + VAT 01530,"Vorderasiatisches Museum, Berlin, Germany",,uncertain,Old Babylonian,"VS 02, 010","Zimmern, Heinrich",1912,...,clay,tablet,,,,,no atf,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,"CT 42, 13",P283740,BM 015794,"British Museum, London, UK",,,Old Babylonian,"CT 42, 13","Figulla, Hugo H.",1959,...,,,,,,,,,,
512,"VS 02, 047",P342855,VAT 01320,"Vorderasiatisches Museum, Berlin, Germany",,,Old Babylonian,"VS 02, 047","Zimmern, Heinrich",1912,...,,,,,,,,,,
513,N 1372,P276518,N 1372,University of Pennsylvania Museum of Archaeolo...,,Nippur,Old Babylonian,"ASJ 14, 032-035","Alster, Bendt",1992,...,clay,tablet,,,,,,,,
514,SLTNi 063,P345194,Ist Ni 02312,"Arkeoloji Müzeleri, Istanbul, Turkey",,Nippur,Old Babylonian,SLTNi 063,"Kramer, Samuel N.",1944,...,clay,tablet,,,,,,,,
515,"VS 10, 134",P342942,VAT 03434,"Vorderasiatisches Museum, Berlin, Germany",,,Old Babylonian,"VS 10, 134","Zimmern, Heinrich",1913,...,clay,tablet,,,,,,,,

In [4]:
cat['museum_no2'] = [re.sub(' 0+', ' ', no) for no in cat.museum_no]
cat['designation2'] = [re.sub(' 0+', ' ', des) for des in cat.designation]

In [13]:
cat['museum_no3'] = [' '.join(no.split()[:2]) for no in cat.museum_no2]

In [14]:
cat[['designation', 'id_text', 'museum_no', 'museum_no2', 'museum_no3', 'designation2']][:10]

,designation,id_text,museum_no,museum_no2,museum_no3,designation2
0,"CT 44, 12",P345521,BM 078175,BM 78175,BM 78175,"CT 44, 12"
1,"TLB 02, 06",P345845,LB 1823,LB 1823,LB 1823,"TLB 2, 6"
2,"CT 42, 08 BM 088288",P283778,BM 088288,BM 88288,BM 88288,"CT 42, 8 BM 88288"
3,"PBS 01/1, 08",P266508,CBS 11359,CBS 11359,CBS 11359,"PBS 1/1, 8"
4,"VS 02, 010",P342818,VAT 01438 + VAT 01529 + VAT 01530,VAT 1438 + VAT 1529 + VAT 1530,VAT 1438,"VS 2, 10"
5,"VS 02, 007 +",P342815,VAT 01337 + VAT 1363 (+) VAT 01567,VAT 1337 + VAT 1363 (+) VAT 1567,VAT 1337,"VS 2, 7 +"
6,"VS 02, 005 +",P342813,VAT 01338 + VAT 01406 + VAT 02164 (+) VAT 03702,VAT 1338 + VAT 1406 + VAT 2164 (+) VAT 3702,VAT 1338,"VS 2, 5 +"
7,"VS 02, 017",P342825,VAT 01346,VAT 1346,VAT 1346,"VS 2, 17"
8,"VS 02, 024",P342832,VAT 01566,VAT 1566,VAT 1566,"VS 2, 24"
9,"VS 10, 102",P342910,VAT 03421 + VAT 03432,VAT 3421 + VAT 3432,VAT 3421,"VS 10, 102"

In [15]:
dict_desig = dict(zip(cat['designation2'], cat['id_text']))
dict_musno = dict(zip(cat['museum_no2'], cat['id_text']))
dict_musno_short = dict(zip(cat['museum_no3'], cat['id_text']))

In [ ]:
dict_musno_short

In [31]:
with open('Delnero_main.txt', 'r', encoding='utf8') as d:
    lit = d.read().splitlines()

In [34]:
Pnos = []
n = 0
for line in lit:
    if line[:2] == '&&':
        l = line.split()
        l = ' '.join(l[:2])
        l = l[2:]
        p = dict_musno_short.get(l, l)
        if p == l:
            p = dict_desig.get(l, l)
            if p == l:
                p = 'unknown'
                n = n+1
        q = [p, l]
        Pnos.append(q)
print(str(len(Pnos)) + ' ; ' + str(n) + ' unknown')

341 ; 37 unknown

In [28]:
Pnos

[['P430946', 'YBC 6822'],
 ['P345455', 'BM 15795'],
 ['P345453', 'BM 15821'],
 ['P274216', 'BM 23111'],
 ['X000102', 'BM 23696'],
 ['P355694', 'BM 24975'],
 ['P223481', 'IM 62827'],
 ['P342834', 'VAT 611'],
 ['P345454', 'BM 29628'],
 ['P274207', 'BM 85206'],
 ['P274237', 'BM 100046'],
 ['P355695', 'BM 29616'],
 ['P345621', 'HS 1494'],
 ['P345696', 'HS 1507'],
 ['P310399', 'YBC 9862'],
 ['P342836', 'VAT 1410'],
 ['P283743', 'BM 16385'],
 ['P345458', 'BM 23117'],
 ['P345457', 'BM 23584'],
 ['P274211', 'BM 23666'],
 ['P274210', 'BM 88406'],
 ['P345741', 'BM 54315'],
 ['P274231', 'BM 54323'],
 ['P342925', 'VAT 3416'],
 ['P274201', 'BM 54970'],
 ['P274209', 'BM 61547'],
 ['P274227', 'BM 66276'],
 ['P274196', 'BM 73137'],
 ['P274268', 'BM 75991'],
 ['P342903', 'VAT 1367'],
 ['P345524', 'BM 78173'],
 ['P342902', 'VAT 1419'],
 ['P283771', 'BM 85198'],
 ['P345522', 'BM 78193'],
 ['P345767', 'BM 78983'],
 ['P342811', 'VAT 604'],
 ['P274198', 'BM 79510'],
 ['P345771', 'BM 80541'],
 ['P274199', 'BM 82972'],
 ['P283775', 'BM 87518'],
 ['P274212', 'BM 87575'],
 ['P274236', 'BM 96112'],
 ['P274229', 'BM 96639'],
 ['P345778', 'BM 96680'],
 ['P345504', 'BM 96933'],
 ['P423962', 'MAH 15995'],
 ['P345779', 'BM 100059'],
 ['P274228', 'BM 100111'],
 ['P355681', 'BM 120011'],
 ['P274214', 'BM 55290'],
 ['P283761', 'BM 54707'],
 ['P345752', 'BM 57654'],
 ['P274232', 'BM 87520'],
 ['P355693', 'AO 3023'],
 ['P345509', 'BM 96681'],
 ['P274200', 'BM 98396'],
 ['P345506', 'BM 96940'],
 ['P274270', 'BM 72884'],
 ['P345721', 'HS 1431'],
 ['unknown', 'HS 1453c'],
 ['P345662', 'HS 1484'],
 ['P279073', 'N 4210'],
 ['unknown', 'HS 2729:'],
 ['unknown', 'HS 2686:'],
 ['unknown', 'HS 2509:'],
 ['unknown', 'HS 2660:'],
 ['P265634', 'CBS 10417'],
 ['P274234', 'BM 81014'],
 ['unknown', 'BM 132267*'],
 ['unknown', 'BM 132267+*'],
 ['P345767', 'BM 78983'],
 ['P342811', 'VAT 604'],
 ['P342809', 'VAT 608'],
 ['P342812', 'VAT 613'],
 ['unknown', 'VAT 615+1394'],
 ['X000110', 'VAT 1365'],
 ['P345419', 'AO 7685'],
 ['P355671', 'YBC 16392'],
 ['P355671', 'YBC 16392'],
 ['P283742', 'BM 15822'],
 ['P274211', 'BM 23666'],
 ['P345771', 'BM 80541'],
 ['P274203', 'BM 80758'],
 ['P274210', 'BM 88406'],
 ['unknown', 'VAT 610+'],
 ['P342855', 'VAT 1320'],
 ['P342851', 'VAT 1336'],
 ['P342900', 'VAT 1364'],
 ['P342883', 'VAT 1372'],
 ['P342882', 'VAT 1377'],
 ['P355665', 'BM 96927'],
 ['P342854', 'VAT 1378'],
 ['P342866', 'VAT 1380'],
 ['P342838', 'VAT 1385'],
 ['P342896', 'VAT 1390'],
 ['P342849', 'VAT 1408'],
 ['P342840', 'VAT 1412'],
 ['P342834', 'VAT 611'],
 ['P342859', 'VAT 1415'],
 ['P342902', 'VAT 1419'],
 ['P342903', 'VAT 1367'],
 ['P345524', 'BM 78173'],
 ['P342902', 'VAT 1419'],
 ['P283771', 'BM 85198'],
 ['P342987', 'VAT 1421'],
 ['P342847', 'VAT 1432'],
 ['P342845', 'VAT 1434'],
 ['P342856', 'VAT 1437'],
 ['P342862', 'VAT 1443'],
 ['P342852', 'VAT 1453'],
 ['unknown', 'VAT 1463'],
 ['P343016', 'VAT 1512'],
 ['unknown', 'VAT 1513'],
 ['P342895', 'VAT 1538'],
 ['P342898', 'VAT 1563'],
 ['P342982', 'VAT 1581'],
 ['P342961', 'VAT 3430'],
 ['P342962', 'VAT 3514'],
 ['P342976', 'VAT 3527'],
 ['P342918', 'VAT 3533'],
 ['P342936', 'VAT 3536'],
 ['P342952', 'VAT 3537'],
 ['P342974', 'VAT 3550'],
 ['P342969', 'VAT 3555'],
 ['P342983', 'VAT 3556'],
 ['P342980', 'VAT 3559'],
 ['P342917', 'VAT 3561'],
 ['unknown', 'VAT 3567+'],
 ['P342991', 'VAT 3570'],
 ['P342967', 'VAT 3574'],
 ['X000111', 'VAT 3578'],
 ['P342990', 'VAT 4596'],
 ['P342835', 'VAT 7032'],
 ['P345349', 'AO 3927'],
 ['P345421', 'AO 7687'],
 ['P345439', 'AO 9070'],
 ['P355659', 'AO 4316'],
 ['P315471', 'AO 4327'],
 ['P315474', 'AO 4328'],
 ['P355652', 'AO 4329'],
 ['P315472', 'AO 4330'],
 ['P355651', 'AO 4331'],
 ['P355655', 'AO 4333'],
 ['P355653', 'AO 4334'],
 ['P315473', 'AO 4336'],
 ['P355650', 'AO 4338'],
 ['P355654', 'AO 4342'],
 ['P355656', 'AO 4345'],
 ['P355660', 'AO 4346'],
 ['P315432', 'AO 13013'],
 ['P257671', 'CBS 106'],
 ['P257677', 'CBS 112'],
 ['P257700', 'CBS 135'],
 ['P257710', 'CBS 145'],
 ['P259101', 'CBS 1781'],
 ['P266483', 'CBS 11326'],
 ['P223457', 'IM 51253'],
 ['P223475', 'IM 54345'],
 ['unknown', 'CNMA 10051'],
 ['P345845', 'LB 1823'],
 ['P274227', 'BM 66276'],
 ['P289914', 'NBC 11433'],
 ['P355670', 'YBC 4659'],
 ['P274275', 'BM 96568'],
 ['P308085', 'YBC 7096'],
 ['P310385', 'YBC 9838'],
 ['unknown', 'UET 6/2,'],
 ['P345452', 'BM 13930'],
 ['P345447', 'BM 13963'],
 ['P283739', 'BM 15793'],
 ['unknown', 'BM 17427'],
 ['P345450', 'BM 22741'],
 ['P345736', 'BM 23104'],
 ['unknown', 'BM 23631'],
 ['P283757', 'BM 29617'],
 ['P345449', 'BM 29623'],
 ['P345451', 'BM 29631'],
 ['P274230', 'BM 57502'],
 ['P274226', 'BM 61445'],
 ['P274197', 'BM 61892'],
 ['P283764', 'BM 65145'],
 ['P283769', 'BM 77952'],
 ['unknown', 'BM 78164'],
 ['P274203', 'BM 80758'],
 ['X000103', 'BM 83719'],
 ['P345456', 'BM 85005'],
 ['P283770', 'BM 85197'],
 ['P283773', 'BM 85204'],
 ['P274207', 'BM 85206'],
 ['P355674', 'BM 86535'],
 ['P283774', 'BM 86536'],
 ['unknown', 'BM 96569'],
 ['unknown', 'BM 96684'],
 ['P345508', 'BM 96691'],
 ['unknown', 'BM 96927:'],
 ['unknown', 'BM 100066:'],
 ['P274233', 'BM 109168'],
 ['unknown', 'BM 120100:'],
 ['unknown', 'UET 6/2,'],
 ['P342816', 'VAT 605'],
 ['P342860', 'VAT 606'],
 ['unknown', 'VAT 609+'],
 ['P343067', 'VAT 1157'],
 ['P342878', 'VAT 1314'],
 ['P342855', 'VAT 1320'],
 ['P342881', 'VAT 1323'],
 ['P342815', 'VAT 1337'],
 ['P342813', 'VAT 1338'],
 ['P342818', 'VAT 1438'],
 ['unknown', 'VAT 1567'],
 ['P342837', 'VAT 1339'],
 ['P342826', 'VAT 1342'],
 ['unknown', 'VAT 1346+'],
 ['unknown', 'VAT 1351'],
 ['P342848', 'VAT 1360'],
 ['P342829', 'VAT 1373'],
 ['P342814', 'VAT 1379'],
 ['P342830', 'VAT 1381'],
 ['unknown', 'VAT 1382+'],
 ['unknown', 'VAT 1387'],
 ['P342850', 'VAT 1389'],
 ['unknown', 'VAT 1395'],
 ['P342822', 'VAT 1407'],
 ['P342827', 'VAT 1423'],
 ['unknown', 'VAT 1430'],
 ['P342844', 'VAT 1462'],
 ['unknown', 'VAT 1463'],
 ['P342817', 'VAT 1465'],
 ['unknown', 'VAT 1513'],
 ['P524997', 'VAT 1533'],
 ['P342869', 'VAT 1544'],
 ['P342831', 'VAT 1564'],
 ['P342832', 'VAT 1566'],
 ['P342989', 'VAT 1574'],
 ['P342910', 'VAT 3421'],
 ['P342911', 'VAT 3423'],
 ['P342912', 'VAT 3425'],
 ['P342935', 'VAT 3433'],
 ['P342943', 'VAT 3435'],
 ['P342919', 'VAT 3551'],
 ['P342981', 'VAT 3589'],
 ['P342909', 'VAT 4112'],
 ['P343003', 'VAT 5448'],
 ['P342931', 'VAT 6077'],
 ['P343000', 'VAT 6530'],
 ['P343006', 'VAT 7760'],
 ['P343070', 'VAT 8201'],
 ['unknown', 'W 16603r'],
 ['P345345', 'AO 3024'],
 ['unknown', 'AO 3924'],
 ['unknown', 'AO 3925'],
 ['P345348', 'AO 3926'],
 ['P345412', 'AO 6905b'],
 ['P345413', 'AO 6906a'],
 ['P345418', 'AO 7684'],
 ['P345420', 'AO 7686'],
 ['unknown', 'AO 4332'],
 ['P315421', 'AO 12999'],
 ['P257610', 'CBS 45'],
 ['unknown', 'CBS 1223'],
 ['P259021', 'CBS 1689'],
 ['P259270', 'CBS 2218'],
 ['P259244', 'CBS 2227'],
 ['P259294', 'CBS 2249'],
 ['unknown', 'CBS 2337:'],
 ['P259314', 'CBS 2281'],
 ['P260028', 'CBS 3656'],
 ['P264319', 'CBS 6890'],
 ['P262310', 'CBS 7285'],
 ['P262930', 'CBS 7990'],
 ['P263346', 'CBS 8547'],
 ['P265348', 'CBS 10084'],
 ['P265349', 'CBS 10085'],
 ['P266078', 'CBS 10885'],
 ['P266312', 'CBS 11151'],
 ['P370896', 'CBS 11178'],
 ['P266481', 'CBS 11321'],
 ['P266485', 'CBS 11328'],
 ['P266495', 'CBS 11344'],
 ['P266500', 'CBS 11349'],
 ['unknown', 'N 3392'],
 ['P267066', 'CBS 11932'],
 ['P269760', 'CBS 15204'],
 ['P276199', 'N 1053'],
 ['P276447', 'N 1296'],
 ['P276471', 'N 1322'],
 ['P277466', 'N 1373'],
 ['P276556', 'N 1411'],
 ['P276657', 'N 1522'],
 ['P277049', 'N 1935'],
 ['P277752', 'N 2684'],
 ['P278047', 'N 2983'],
 ['P278106', 'N 3043'],
 ['P278132', 'N 3073'],
 ['P278183', 'N 3127'],
 ['P278218', 'N 3164'],
 ['P278359', 'N 3316'],
 ['P278371', 'N 3329'],
 ['P278373', 'N 3332'],
 ['P278417', 'N 3338'],
 ['P278414', 'N 3348'],
 ['P278398', 'N 3358'],
 ['P278424', 'N 3388'],
 ['P278426', 'N 3390'],
 ['P278431', 'N 3396'],
 ['unknown', 'N 3556,'],
 ['P278623', 'N 3605'],
 ['P278634', 'N 3616'],
 ['P275008', 'N 3655'],
 ['P278698', 'N 3683'],
 ['P275010', 'N 4100'],
 ['P278999', 'N 4124'],
 ['P279029', 'N 4163'],
 ['P279055', 'N 4190'],
 ['P275011', 'N 4204'],
 ['unknown', 'N 4216,'],
 ['unknown', 'N 5450,'],
 ['P281009', 'N 7276'],
 ['unknown', 'N 7458,'],
 ['unknown', 'N 7816,'],
 ['P281578', 'N 7854'],
 ['P255417', 'UM 29-13-468'],
 ['P255527', 'UM 29-13-596'],
 ['P256178', 'UM 29-15-368'],
 ['unknown', 'UM 29-16-532,'],
 ['unknown', 'UM 29-16-762,'],
 ['unknown', 'MIO 1577'],
 ['unknown', 'MIO 2273'],
 ['unknown', 'MIO 2327'],
 ['unknown', 'IM 13404'],
 ['P355666', 'IM 44737'],
 ['unknown', 'IM 51250'],
 ['unknown', 'IM 54616'],
 ['P423975', 'MAH 16014'],
 ['P355682', 'MAH 16016'],
 ['P424008', 'MAH 16066'],
 ['unknown', 'CNMA 10050'],
 ['unknown', 'MMA 86.11.62'],
 ['unknown', 'HSM 3625'],
 ['unknown', 'RA 15'],
 ['unknown', 'RA 17:']]

341